# Generated by Django 4.2.2 on 2023-06-14 06:19

from django.db import migrations, models
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('short_desc', models.TextField(max_length=500)),
                ('blog_body', tinymce.models.HTMLField()),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('created_on', models.DateField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
