name: Deploy app to the server

on:
  push:
    branch:
      - master

name: Deploy on push
jobs:
  web-deploy:
    name: Deploying job
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2

    - name: Sync files
      uses: 
      with: 
        server: ftp.devamcareerhub.com
        username: ${{secrets.ftp_username}}
        password: ${{secrets.ftp_password}}
        server-dir: /home/devamcar/dch_website/dch/

